### ISSUE TITLE
Failure to install mongo-orchestration on Amazon Linux with Python 2.6

### ISSUE THREAD

**Issue by ShaneHarvey** [mongodb-labs/drivers-evergreen-tools#43]
```
[2018/05/23 10:43:16.398] + pip install --upgrade git+git://github.com/mongodb/mongo-orchestration@master
 [2018/05/23 10:43:16.678] DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
 [2018/05/23 10:43:16.684] Installing setuptools<37, pip, wheel<0.30...done.
 [2018/05/23 10:43:16.684] Collecting git+git://github.com/mongodb/mongo-orchestration@master
 [2018/05/23 10:43:16.685]   Cloning git://github.com/mongodb/mongo-orchestration (to master) to ./db/pip-XMN79s-build
 [2018/05/23 10:43:17.385] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:17.385]   SNIMissingWarning
 [2018/05/23 10:43:17.385] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:17.385]   InsecurePlatformWarning
 [2018/05/23 10:43:17.405] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:17.405]   InsecurePlatformWarning
 [2018/05/23 10:43:18.214] Requirement already up-to-date: pymongo<3.6.0,>=3.0.2 in /usr/lib64/python2.6/site-packages (from mongo-orchestration==0.6.11)
 [2018/05/23 10:43:18.298] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:18.298]   InsecurePlatformWarning
 [2018/05/23 10:43:18.370] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:18.370]   InsecurePlatformWarning
 [2018/05/23 10:43:18.377]   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:491: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),)': /packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz
 [2018/05/23 10:43:18.379] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:18.379]   InsecurePlatformWarning
 [2018/05/23 10:43:18.888]   Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:491: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),)': /packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz
 [2018/05/23 10:43:18.889] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:18.889]   InsecurePlatformWarning
 [2018/05/23 10:43:19.899]   Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:491: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),)': /packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz
 [2018/05/23 10:43:19.901] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:19.901]   InsecurePlatformWarning
 [2018/05/23 10:43:21.910]   Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:491: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),)': /packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz
 [2018/05/23 10:43:21.911] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:21.911]   InsecurePlatformWarning
 [2018/05/23 10:43:25.923]   Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '_ssl.c:491: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),)': /packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz
 [2018/05/23 10:43:25.925] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:25.925]   InsecurePlatformWarning
 [2018/05/23 10:43:25.944] Exception:
 [2018/05/23 10:43:25.944] Traceback (most recent call last):
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/basecommand.py", line 215, in main
 [2018/05/23 10:43:25.944]     status = self.run(options, args)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/commands/install.py", line 335, in run
 [2018/05/23 10:43:25.944]     wb.build(autobuilding=True)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/wheel.py", line 749, in build
 [2018/05/23 10:43:25.944]     self.requirement_set.prepare_files(self.finder)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
 [2018/05/23 10:43:25.944]     ignore_dependencies=self.ignore_dependencies))
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
 [2018/05/23 10:43:25.944]     session=self.session, hashes=hashes)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/download.py", line 821, in unpack_url
 [2018/05/23 10:43:25.944]     hashes=hashes
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/download.py", line 659, in unpack_http_url
 [2018/05/23 10:43:25.944]     hashes)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/download.py", line 853, in _download_http_url
 [2018/05/23 10:43:25.944]     stream=True,
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
 [2018/05/23 10:43:25.944]     return self.request('GET', url, **kwargs)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/download.py", line 386, in request
 [2018/05/23 10:43:25.944]     return super(PipSession, self).request(method, url, *args, **kwargs)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
 [2018/05/23 10:43:25.944]     resp = self.send(prep, **send_kwargs)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/sessions.py", line 618, in send
 [2018/05/23 10:43:25.944]     r = adapter.send(request, **kwargs)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
 [2018/05/23 10:43:25.944]     resp = super(CacheControlAdapter, self).send(request, **kw)
 [2018/05/23 10:43:25.944]   File "/data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/adapters.py", line 506, in send
 [2018/05/23 10:43:25.944]     raise SSLError(e, request=request)
 [2018/05/23 10:43:25.944] SSLError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz (Caused by SSLError(SSLError(1, '_ssl.c:491: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
 [2018/05/23 10:43:26.020] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:26.020]   InsecurePlatformWarning
 [2018/05/23 10:43:26.038] /data/mci/990a07987d5723ebf1ca6d02a5d77ee9/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
 [2018/05/23 10:43:26.038]   InsecurePlatformWarning
 [2018/05/23 10:43:26.079] You are using pip version 9.0.3, however version 10.0.1 is available.
 [2018/05/23 10:43:26.079] You should consider upgrading via the 'pip install --upgrade pip' command.
 [2018/05/23 10:43:26.112] Collecting bottle>=0.12.7 (from mongo-orchestration==0.6.11)
 [2018/05/23 10:43:26.112] Command failed: command [pid=2101] encountered problem: exit status 2
```

**Comment by ShaneHarvey** [comment]
We should use Python from the toolchain (`/opt/mongodbtoolchain/v2/bin`) to run mongo-orchestration.

**Comment by ShaneHarvey** [comment]
Note, Amazon linux is still failing because of https://jira.mongodb.org/browse/BUILD-5581

**Comment by ShaneHarvey** [comment]
Reverted the change to use the toolchain's python because it uses OpenSSL 0.9.8 on Mac and fails to install MO:
```
[2018/05/24 14:13:50.985] + PYTHON=/opt/mongodbtoolchain/v2/bin/python3
[2018/05/24 14:13:51.283] + /opt/mongodbtoolchain/v2/bin/python3 -c 'import sys; print(sys.version)'
[2018/05/24 14:13:51.280] 3.6.0 (default, Dec 27 2017, 12:49:15)
[2018/05/24 14:13:51.280] [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
[2018/05/24 14:13:51.283] + /opt/mongodbtoolchain/v2/bin/python3 -c 'import ssl; print(ssl.OPENSSL_VERSION)'
[2018/05/24 14:13:51.998] OpenSSL 0.9.8zh 14 Jan 2016
...
[2018/05/24 14:13:54.542] + pip install --upgrade git+git://github.com/mongodb/mongo-orchestration@master
[2018/05/24 14:13:55.073] Installing setuptools, pip, wheel...done.
[2018/05/24 14:13:55.073] Collecting git+git://github.com/mongodb/mongo-orchestration@master
[2018/05/24 14:13:55.074]   Cloning git://github.com/mongodb/mongo-orchestration (to master) to /private/var/folders/g2/fbs09lrd6yb1l4b6361g30q40000gm/T/pip-jf8zy9gq-build
[2018/05/24 14:13:56.028] Collecting pymongo<3.6.0,>=3.0.2 (from mongo-orchestration==0.6.11)
[2018/05/24 14:13:56.028]   Could not fetch URL https://pypi.python.org/simple/pymongo/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:749) - skipping
[2018/05/24 14:13:56.029]   Cache entry deserialization failed, entry ignored
[2018/05/24 14:13:56.029]   Could not find a version that satisfies the requirement pymongo<3.6.0,>=3.0.2 (from mongo-orchestration==0.6.11) (from versions: )
[2018/05/24 14:13:56.038] No matching distribution found for pymongo<3.6.0,>=3.0.2 (from mongo-orchestration==0.6.11)
[2018/05/24 14:13:56.131] Command failed: command [pid=24539] encountered problem: exit status 1
```

**Comment by ShaneHarvey** [comment]
The MacOS toolchain was updated to use OpenSSL 1.0.2 in https://jira.mongodb.org/browse/BUILD-5464. https://jira.mongodb.org/browse/BUILD-5606 tracks actually deploying the new toolchain.

**Comment by ShaneHarvey** [comment]
We should fix this issue. Installation is now failing on RHEL 6.2 because the default python 2.6 fails to install mongo-orchestration:

```
[2020/05/19 17:52:24.957] + cd /data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration
[2020/05/19 17:52:24.957] + '[' -f venv/bin/activate ']'
[2020/05/19 17:52:24.957] + '[' -f venv/Scripts/activate ']'
[2020/05/19 17:52:24.957] + python -m virtualenv --system-site-packages --never-download venv
[2020/05/19 17:52:25.307] /data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027
[2020/05/19 17:52:25.307] New python executable in /data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/bin/python
[2020/05/19 17:52:28.375] + '[' -f venv/bin/activate ']'
[2020/05/19 17:52:28.375] + . venv/bin/activate
[2020/05/19 17:52:28.375] ++ deactivate nondestructive
[2020/05/19 17:52:28.375] ++ unset -f pydoc
[2020/05/19 17:52:28.375] ++ '[' -z '' ']'
[2020/05/19 17:52:28.375] ++ '[' -z '' ']'
[2020/05/19 17:52:28.375] ++ '[' -n /bin/sh ']'
[2020/05/19 17:52:28.375] ++ hash -r
[2020/05/19 17:52:28.375] ++ '[' -z '' ']'
[2020/05/19 17:52:28.375] ++ unset VIRTUAL_ENV
[2020/05/19 17:52:28.375] ++ '[' '!' nondestructive = nondestructive ']'
[2020/05/19 17:52:28.375] ++ VIRTUAL_ENV=/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv
[2020/05/19 17:52:28.375] ++ export VIRTUAL_ENV
[2020/05/19 17:52:28.375] ++ _OLD_VIRTUAL_PATH=/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/mongodb/bin:/opt/go/bin:/opt/go/bin:/usr/lib64/icecc/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/opt/node/bin:/root/bin:/opt/node/bin
[2020/05/19 17:52:28.375] ++ PATH=/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/bin:/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/mongodb/bin:/opt/go/bin:/opt/go/bin:/usr/lib64/icecc/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/opt/node/bin:/root/bin:/opt/node/bin
[2020/05/19 17:52:28.375] ++ export PATH
[2020/05/19 17:52:28.376] ++ '[' -z '' ']'
[2020/05/19 17:52:28.376] ++ '[' -z '' ']'
[2020/05/19 17:52:28.376] ++ _OLD_VIRTUAL_PS1=
[2020/05/19 17:52:28.376] ++ '[' x '!=' x ']'
[2020/05/19 17:52:28.376] +++ basename /data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv
[2020/05/19 17:52:28.376] ++ PS1='(venv) '
[2020/05/19 17:52:28.376] ++ export PS1
[2020/05/19 17:52:28.376] ++ alias pydoc
[2020/05/19 17:52:28.376] ++ '[' -n /bin/sh ']'
[2020/05/19 17:52:28.376] ++ hash -r
[2020/05/19 17:52:28.376] + pip install --upgrade git+git://github.com/mongodb/mongo-orchestration@master
[2020/05/19 17:52:28.713] DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
[2020/05/19 17:52:28.734] Installing setuptools<37, pip, wheel<0.30...done.
[2020/05/19 17:52:28.734] Collecting git+git://github.com/mongodb/mongo-orchestration@master
[2020/05/19 17:52:28.735]   Cloning git://github.com/mongodb/mongo-orchestration (to master) to ./db/pip-RXIdun-build
[2020/05/19 17:52:29.440] /data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2020/05/19 17:52:29.440]   SNIMissingWarning
[2020/05/19 17:52:29.440] /data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2020/05/19 17:52:29.440]   InsecurePlatformWarning
[2020/05/19 17:52:30.322] Cache entry deserialization failed, entry ignored
[2020/05/19 17:52:30.322] /data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2020/05/19 17:52:30.322]   InsecurePlatformWarning
[2020/05/19 17:52:30.471] Exception:
[2020/05/19 17:52:30.471] Traceback (most recent call last):
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/basecommand.py", line 215, in main
[2020/05/19 17:52:30.471]     status = self.run(options, args)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/commands/install.py", line 335, in run
[2020/05/19 17:52:30.471]     wb.build(autobuilding=True)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/wheel.py", line 749, in build
[2020/05/19 17:52:30.471]     self.requirement_set.prepare_files(self.finder)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
[2020/05/19 17:52:30.471]     ignore_dependencies=self.ignore_dependencies))
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/req/req_set.py", line 487, in _prepare_file
[2020/05/19 17:52:30.471]     req_to_install, finder)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/req/req_set.py", line 428, in _check_skip_installed
[2020/05/19 17:52:30.471]     req_to_install, upgrade_allowed)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/index.py", line 465, in find_requirement
[2020/05/19 17:52:30.471]     all_candidates = self.find_all_candidates(req.name)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/index.py", line 423, in find_all_candidates
[2020/05/19 17:52:30.471]     for page in self._get_pages(url_locations, project_name):
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/index.py", line 568, in _get_pages
[2020/05/19 17:52:30.471]     page = self._get_page(location)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/index.py", line 683, in _get_page
[2020/05/19 17:52:30.471]     return HTMLPage.get_page(link, session=self.session)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/index.py", line 792, in get_page
[2020/05/19 17:52:30.471]     "Cache-Control": "max-age=600",
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/sessions.py", line 521, in get
[2020/05/19 17:52:30.471]     return self.request('GET', url, **kwargs)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/download.py", line 386, in request
[2020/05/19 17:52:30.471]     return super(PipSession, self).request(method, url, *args, **kwargs)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/sessions.py", line 508, in request
[2020/05/19 17:52:30.471]     resp = self.send(prep, **send_kwargs)
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/sessions.py", line 658, in send
[2020/05/19 17:52:30.471]     r.content
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/models.py", line 823, in content
[2020/05/19 17:52:30.471]     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
[2020/05/19 17:52:30.471]   File "/data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/requests/models.py", line 748, in generate
[2020/05/19 17:52:30.472]     raise ChunkedEncodingError(e)
[2020/05/19 17:52:30.472] ChunkedEncodingError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
[2020/05/19 17:52:30.557] /data/mci/ea79d0d3e9a55d3d5bc8fac0117ed027/drivers-tools/.evergreen/orchestration/venv/lib/python2.6/site-packages/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[2020/05/19 17:52:30.557]   InsecurePlatformWarning
[2020/05/19 17:52:30.709] You are using pip version 9.0.3, however version 20.1.1 is available.
[2020/05/19 17:52:30.709] You should consider upgrading via the 'pip install --upgrade pip' command.
[2020/05/19 17:52:30.760] Command failed: command encountered problem: error waiting on process '8ca4d7fb-2de1-40fc-afce-ead6b6978b9d': exit status 2
[2020/05/19 17:52:30.760] Task completed - FAILURE.
```
