### ISSUE TITLE
macOS fails to install virtualenv

### ISSUE THREAD

**Issue by ShaneHarvey** [mongodb-labs/drivers-evergreen-tools#76]
Failures:
```
 [2019/11/21 16:17:15.018] + python -m virtualenv --system-site-packages --never-download venv
 [2019/11/21 16:17:15.117] ERROR:root:code for hash md5 was not found.
 [2019/11/21 16:17:15.117] Traceback (most recent call last):
 [2019/11/21 16:17:15.117]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.117]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.117]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.117]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.117] ValueError: unsupported hash type md5
 [2019/11/21 16:17:15.118] ERROR:root:code for hash sha1 was not found.
 [2019/11/21 16:17:15.118] Traceback (most recent call last):
 [2019/11/21 16:17:15.118]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.118]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.118]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.118]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.118] ValueError: unsupported hash type sha1
 [2019/11/21 16:17:15.118] ERROR:root:code for hash sha224 was not found.
 [2019/11/21 16:17:15.118] Traceback (most recent call last):
 [2019/11/21 16:17:15.118]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.118]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.118]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.118]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.118] ValueError: unsupported hash type sha224
 [2019/11/21 16:17:15.118] ERROR:root:code for hash sha256 was not found.
 [2019/11/21 16:17:15.118] Traceback (most recent call last):
 [2019/11/21 16:17:15.118]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.118]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.118]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.118]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.118] ValueError: unsupported hash type sha256
 [2019/11/21 16:17:15.119] ERROR:root:code for hash sha384 was not found.
 [2019/11/21 16:17:15.119] Traceback (most recent call last):
 [2019/11/21 16:17:15.119]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.119]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.119]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.119]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.119] ValueError: unsupported hash type sha384
 [2019/11/21 16:17:15.119] ERROR:root:code for hash sha512 was not found.
 [2019/11/21 16:17:15.119] Traceback (most recent call last):
 [2019/11/21 16:17:15.119]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.119]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.119]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.119]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.119] ValueError: unsupported hash type sha512
 [2019/11/21 16:17:15.331] Traceback (most recent call last):
 [2019/11/21 16:17:15.331]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
 [2019/11/21 16:17:15.331]     "__main__", fname, loader, pkg_name)
 [2019/11/21 16:17:15.331]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
 [2019/11/21 16:17:15.331]     exec code in run_globals
 [2019/11/21 16:17:15.331]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 2628, in <module>
 [2019/11/21 16:17:15.331] /data/mci/9d1cdc3e5aeebdd145271827fc5dff1f
 [2019/11/21 16:17:15.331] New python executable in /data/mci/9d1cdc3e5aeebdd145271827fc5dff1f/drivers-tools/.evergreen/orchestration/venv/bin/python2.7
 [2019/11/21 16:17:15.331] Also creating executable in /data/mci/9d1cdc3e5aeebdd145271827fc5dff1f/drivers-tools/.evergreen/orchestration/venv/bin/python
 [2019/11/21 16:17:15.331] Command /data/mci/9d1cdc3e5a...n/venv/bin/python2.7 -m pip config list had error code 1
 [2019/11/21 16:17:15.332]     main()
 [2019/11/21 16:17:15.332]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 870, in main
 [2019/11/21 16:17:15.505]     symlink=options.symlink,
 [2019/11/21 16:17:15.505]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1173, in create_environment
 [2019/11/21 16:17:15.505]     install_wheel(to_install, py_executable, search_dirs, download=download)
 [2019/11/21 16:17:15.505]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1019, in install_wheel
 [2019/11/21 16:17:15.505]     _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
 [2019/11/21 16:17:15.505]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1046, in _install_wheel_with_search_dir
 [2019/11/21 16:17:15.505]     config = _pip_config(py_executable, python_path)
 [2019/11/21 16:17:15.505]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1128, in _pip_config
 [2019/11/21 16:17:15.505]     config[key] = ast.literal_eval(value)
 [2019/11/21 16:17:15.505]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 49, in literal_eval
 [2019/11/21 16:17:15.505]     node_or_string = parse(node_or_string, mode='eval')
 [2019/11/21 16:17:15.505]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
 [2019/11/21 16:17:15.505]     return compile(source, filename, mode, PyCF_ONLY_AST)
 [2019/11/21 16:17:15.505]   File "<unknown>", line 1
 [2019/11/21 16:17:15.505]     __get_hash(__func_name)
 [2019/11/21 16:17:15.505]     ^
 [2019/11/21 16:17:15.505] IndentationError: unexpected indent
 [2019/11/21 16:17:15.505] + virtualenv --system-site-packages --never-download venv
 [2019/11/21 16:17:15.505] ERROR:root:code for hash md5 was not found.
 [2019/11/21 16:17:15.505] Traceback (most recent call last):
 [2019/11/21 16:17:15.505]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.505]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.505]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.505]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.505] ValueError: unsupported hash type md5
 [2019/11/21 16:17:15.505] ERROR:root:code for hash sha1 was not found.
 [2019/11/21 16:17:15.505] Traceback (most recent call last):
 [2019/11/21 16:17:15.505]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.506]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.506]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.506] ValueError: unsupported hash type sha1
 [2019/11/21 16:17:15.506] ERROR:root:code for hash sha224 was not found.
 [2019/11/21 16:17:15.506] Traceback (most recent call last):
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.506]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.506]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.506] ValueError: unsupported hash type sha224
 [2019/11/21 16:17:15.506] ERROR:root:code for hash sha256 was not found.
 [2019/11/21 16:17:15.506] Traceback (most recent call last):
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.506]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.506]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.506] ValueError: unsupported hash type sha256
 [2019/11/21 16:17:15.506] ERROR:root:code for hash sha384 was not found.
 [2019/11/21 16:17:15.506] Traceback (most recent call last):
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.506]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.506]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.506] ValueError: unsupported hash type sha384
 [2019/11/21 16:17:15.506] ERROR:root:code for hash sha512 was not found.
 [2019/11/21 16:17:15.506] Traceback (most recent call last):
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
 [2019/11/21 16:17:15.506]     globals()[__func_name] = __get_hash(__func_name)
 [2019/11/21 16:17:15.506]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
 [2019/11/21 16:17:15.506]     raise ValueError('unsupported hash type ' + name)
 [2019/11/21 16:17:15.506] ValueError: unsupported hash type sha512
 [2019/11/21 16:17:15.525] New python executable in /data/mci/9d1cdc3e5aeebdd145271827fc5dff1f/drivers-tools/.evergreen/orchestration/venv/bin/python2.7
 [2019/11/21 16:17:15.525] Not overwriting existing python script /data/mci/9d1cdc3e5aeebdd145271827fc5dff1f/drivers-tools/.evergreen/orchestration/venv/bin/python (you must use /data/mci/9d1cdc3e5aeebdd145271827fc5dff1f/drivers-tools/.evergreen/orchestration/venv/bin/python2.7)
 [2019/11/21 16:17:15.525] Command /data/mci/9d1cdc3e5a...n/venv/bin/python2.7 -m pip config list had error code 1
 [2019/11/21 16:17:15.525] Traceback (most recent call last):
 [2019/11/21 16:17:15.525]   File "/usr/local/bin/virtualenv", line 11, in <module>
 [2019/11/21 16:17:15.525]     sys.exit(main())
 [2019/11/21 16:17:15.525]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 870, in main
 [2019/11/21 16:17:15.525]     symlink=options.symlink,
 [2019/11/21 16:17:15.525]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1173, in create_environment
 [2019/11/21 16:17:15.525]     install_wheel(to_install, py_executable, search_dirs, download=download)
 [2019/11/21 16:17:15.525]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1019, in install_wheel
 [2019/11/21 16:17:15.525]     _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
 [2019/11/21 16:17:15.525]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1046, in _install_wheel_with_search_dir
 [2019/11/21 16:17:15.525]     config = _pip_config(py_executable, python_path)
 [2019/11/21 16:17:15.525]   File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 1128, in _pip_config
 [2019/11/21 16:17:15.526]     config[key] = ast.literal_eval(value)
 [2019/11/21 16:17:15.526]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 49, in literal_eval
 [2019/11/21 16:17:15.526]     node_or_string = parse(node_or_string, mode='eval')
 [2019/11/21 16:17:15.526]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 37, in parse
 [2019/11/21 16:17:15.526]     return compile(source, filename, mode, PyCF_ONLY_AST)
 [2019/11/21 16:17:15.526]   File "<unknown>", line 1
 [2019/11/21 16:17:15.526]     __get_hash(__func_name)
 [2019/11/21 16:17:15.526]     ^
 [2019/11/21 16:17:15.533] IndentationError: unexpected indent

```
https://evergreen.mongodb.com/task/mongo_python_driver_test_macos__platform~macos_1012_auth~auth_ssl~nossl_test_3.0_standalone_ec4b02052d790b18df832194eeb6cddc66f9047d_19_11_21_20_15_12

**Comment by ShaneHarvey** [comment]
I think the problem may be that we're somehow using the brew installed python 2.7:
```
 [2019/11/21 16:17:15.117]   File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
```

**Comment by ShaneHarvey** [comment]
This was a configuration issue that was fixed by the build team.
